### PR TITLE
Closes #5

### LINKED ISSUE #5: Update to coveralls ^1.0
and use after_success instead of after_script for it

### PR DESCRIPTION
**Pull request by bweston92**

### CODE REVIEW

**Comment by sandrokeil** [comment]
@bweston92 Thank you for the PR, but I guess you have to fix the .coveralls.yml too. The build has failed.

**Comment by bweston92** [comment]
@sandrokeil failed due to no "tests" directory, will remove from `.php_cs`.

**Comment by sandrokeil** [comment]
@bweston92 Please remove also the [src_dir](https://github.com/prooph/laravel-package/blob/master/.coveralls.yml#L3) definition. I think there was an issue too. Then I will merge it. Thank you very much.

**Comment by bweston92** [comment]
Done, just running tests.

**Comment by sandrokeil** [comment]
:+1:

**Pull request merged**
